#Ist nur dafuer gedacht sich die Daten die in der in memory H2 datenbank anzusehen

spring.datasource.url=jdbc:h2:/tmp/liquibase-demo4
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
